# Generated by Django 4.1.7 on 2023-02-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bookimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
