# Generated by Django 4.1.7 on 2023-03-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_task_bookimage_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bookimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
