# Generated by Django 4.1.7 on 2023-03-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_alter_task_bookimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bookimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
