# Generated by Django 4.1.7 on 2023-03-18 13:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookapp', '0005_alter_task_bookimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='BookModel',
        ),
    ]
